apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
  name: wordpress
spec:
  selector:
    app: wordpress
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP